### PR TITLE
[SUGGESTION] patch sanity_check_paths['files'] to look in lib/ and lib64/

### LINKED ISSUE #1404: provide generic way for sanity_check to look in both `lib` and `lib64` for library files
AFAIK the only way of checking whether library files ended up in `lib/` or `lib64/` is via

``` .py
sanity_check_paths = {
  'files': [
    ('lib/myLib.so', 'lib64/myLib.so'),
    ('lib/myLib.a', 'lib64/myLib.a')
  ]
}
```

Wouldn't it be nice having this collapsing into something like

``` .py
sanity_check_paths = {
  'files': [
    LibraryPathBuilder('myLib', shared=True, static=True)
  ]
}
```

It's less error prone to typos and way less tedious.

### PR DESCRIPTION
**Pull request by torbjoernk**
This is a suggestion to fix #1404.
Don't know whether it breaks something elsewhere ...

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@torbjoernk: this is an interesting idea... Did @berndmohr put you up to this? ;-)

I had something more elaborate in mind, i.e. add support for additional keys like `libs` or `libraries` to be specified in `sanity_check_paths`, which then enables us to check both in `lib` and `lib64` automagically; this has been an idea for a *long* time (see #196), but it has never materialised.

Nevertheless, I like this approach, since it's a quick-and-easy fix for something that has annoyed a lot of people (mostly on SuSE and derivatives), and shouldn't do any harm. We already consider both `lib` and `lib64` for `$LD_LIBRARY_PATH` and `$LIBRARY_PATH`, for example.

@wpoely86, @rjeschmi, @fgeorgatos, @pescobar, @ocaisa, @JensTimmerman: thoughts?

**Comment by wpoely86** [comment]
I feel more for the #196 approach... It cannot be that hard to implement?

**Comment by boegel** [comment]
@wpoely86: I don't feel this excludes the need for #196. It's a quick and imho harmless fix to a real problem. Implementing #196 would still require updating *a lot* of easyconfig files...

**Comment by wpoely86** [comment]
#196 can perfectly be done in a backwards compatibly way. Adding a libraries section doesn't invalidate the current `files`.

**Comment by boegel** [comment]
@wpoely86: sure, but introduces a `libraries` key is only adding support for a fix (which requires reworking lots of easyconfig files), while this trick is an actual fix for the problem at hand (and doesn't rule out working in `libraries` in the coming future)

**Comment by akesandgren** [comment]
Is this still valid or should it be closed?
If still valid the code needs a slight adjustment, don't use "/", use os.pathsep (or whatever it is called)
And it should go both ways...

**Comment by boegel** [comment]
@akesandgren This is no longer relevant, so I'll go ahead and close it.

Fallback to also consider `lib64` for `lib` paths (and vice versa) was implemented in #2477 (and enabled by default, with a switch to disable it) .

This PR did serve as inspiration for that change though, so I'd like to thank @torbjoernk for this...

**Pull request closed without merging**
