### PR TITLE
make intelfftw toolchain component aware of GCCcore

### PR DESCRIPTION
**Pull request by SebastianAchilles**

### CODE REVIEW

**Comment by boegel** [comment]
@SebastianAchilles Looks fine, but can you provide some more context (in the PR description)?

Where did you ran into this exactly?

**Comment by SebastianAchilles** [comment]
This EasyBlock change is required for JSC's custom toolchain `gcccoremkl`. Which is using `mkl` at the `GCCcore` level.
I opened this PR to reduce the custom EasyBlocks.
This is currently used at ComputeCanada: https://github.com/ComputeCanada/easybuild-framework/blob/computecanada-main/easybuild/toolchains/fft/intelfftw.py#L65
and JSC: https://github.com/easybuilders/JSC/blob/2020/Custom_Toolchains/fft/intelfftw.py#L65

**Comment by boegel** [comment]
Thanks for the clarification @SebastianAchilles !

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
