### PR TITLE
Don't skip sanity check for --module-only --rebuild

### PR DESCRIPTION
**Pull request by Flamefire**
The only difference to now us that the sanity check is run when `--rebuild` is used.
For "proper" use, i.e. regenerating a module, this does not cause any problems and might even show issues that user was not aware of.
For those that used it for something else, the sanity check can fail and those need to use `--force` instead.
So that is IMO very low impact.

I'd even say it is a bugfix as the comment states: "allow skipping sanity check too when only generating module and force is used"

### CODE REVIEW

**Comment by smoors** [comment]
I'm in favor of this change, it's indeed useful to still (re)do the sanity checks with `--module-only`.
it would be nice if the same could be done for extensions, as the sanity checks for those are also skipped currently.

**Comment by boegel** [comment]
@smoors The sanity check for extensions are always skipped when using `--module-only` right now (even without `--force` or `--rebuild`), which is sort of a feature (although you could argue it's a bug).

If we change/fix that, we would definitely need an `--skip-exts` or something too.

**Comment by ocaisa** [comment]
I'm a bit confused by this because I spent all day yesterday using `--module-only --rebuild` exactly because it does the sanity checks.

**Comment by Flamefire** [comment]
@ocaisa : What exactly is the behavior you want? NOT running the sanity check when module-only is used? You can use `--module-only --force` for that. Everything else (e.g. `--module-only`) does run the sanity check (after this change also for `--module-only --rebuild`)
Maybe bring it up in the conf call in a few mins?

**Comment by ocaisa** [comment]
> @ocaisa : What exactly is the behavior you want? NOT running the sanity check when module-only is used? You can use `--module-only --force` for that. Everything else (e.g. `--module-only`) does run the sanity check (after this change also for `--module-only --rebuild`)
> Maybe bring it up in the conf call in a few mins?

I updated my comment, I was wrong in what I originally said. I definitely agree that running the sanity check should be done when combining `--module-only` and `--rebuild`, see https://github.com/easybuilders/easybuild-easyconfigs/issues/12760 for why I think this would be useful

**Review by ocaisa — APPROVED** [review]

**Comment by ocaisa** [comment]
@Flamefire Do you think you will implement the `--skip-exts` option? For me this is a nice to have and if you don't have time we can create an issue for it.

Personally I believe you should run the sanity checks for extensions too. The R extensions in `R/4.0.0-foss-2020a` have changed multiple times, so if you built with 4.3.2 but do a rebuild with 4.3.4, the module will report modules that are in fact not installed.

**Comment by Flamefire** [comment]
@ocaisa Makes sense to run the sanity check for extensions too. Not sure if or when I have time for that, so do create an issue for this and if someone works on that soon, then the better

**Pull request merged**
