### PR TITLE
deprecate use of CMake

### PR DESCRIPTION
**Pull request by boegelbot**
I'm sick of reporting installation problems that arise in easyconfig pull requests that can be basically brought down to the use of CMake as configuration tool, so it's time to take some measures...

Let's deprecate the use of CMake, and recommend users to use alternatives like SCons or Bazel, or to make a request to the developers of the software they want to install to do so.

### CODE REVIEW

**Comment by akesandgren** [comment]
While we're at it, let's deprecate Fortran and use Snowball instead.

**Comment by migueldiascosta** [comment]
@boegelbot thank you for your first PR! your contributions to the easybuild community have been invaluable and we've been wondering when you'd take the natural step to contribute with actual code. Looking forward to see what else you have in store for us!

**Review by smoors — APPROVED** [review]
LGTM

**Comment by klust** [comment]
Excellent idea, but I would skip SCons. The world would be so much better if there would be only one tool, so let's restrict ourselves to Bazel. After all, why would one want to die from CMake Cancer if the Bazel Bubonic Plague can kill you so much more efficiently? And if people want support: The answer is simple: "Ask Google".

**Comment by dianaiusan** [comment]
This was fun, @boegelbot.

**Comment by pescobar** [comment]
Fully agree with @klust . We should only support Bazel.

**Comment by branfosj** [comment]
Closing the April Fools

**Pull request closed without merging**
