### PR TITLE
Use default value `$XDG_CONFIG_DIRS` from XDG basedir spec: `/etc/xdg` (instead of `/etc`)

### PR DESCRIPTION
**Pull request by runiq**
The [spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables) mandates `/etc/xdg` instead of `/etc` for the default value of `XDG_CONFIG_DIRS`.

I'm pretty sure this requires documentation changes because this is potentially a breaking change, but I'm not entirely sure where. I hope a project member can point me to where. :no_mouth::sweat_drops:

Fixes https://github.com/easybuilders/easybuild-framework/issues/4581

### CODE REVIEW

**Comment by boegel** [comment]
Since we're not following the spec w.r.t. the default value if `$XDG_CONFIG_DIRS` we should indeed fix this, but we should also try and limit the impact of this change.

We could for example at least print a warning message when we find one or more configuration files at `/etc/easybuild.d/*.cfg` (but only when `$XDG_CONFIG_DIRS` is *not* set?) to indicate that those configuration files will now be ignored, and that they should be moved to `/etc/xdg/easybuild.d/*.cfg`?

**Comment by boegel** [comment]
We could print a warning if `$XDG_CONFIG_DIRS` is not defined and `*.cfg` files are found in `/etc/easybuild.d/`, which instructs the user to define `$XDG_CONFIG_DIRS` to `/etc` as workaround (which will affect other stuff too though), or move those configuration files to `/etc/xdg/easybuild.d/`.

**Review by bartoldeman — COMMENTED** [review]
LGTM

**Review by bartoldeman — APPROVED** [review]
LGTM

**Pull request merged**
