### PR TITLE
create `lib` -> `lib64` symlink (or vice versa) *before* running `postinstallcmds`

### PR DESCRIPTION
**Pull request by ocaisa**
Not having the symlinks in place means that `postinstallcmds` that rely on using/modifying something in the library directory have to use tricks to figure out the correct location.

### CODE REVIEW

**Comment by ocaisa** [comment]
See https://github.com/easybuilders/easybuild-easyconfigs/pull/19386 and libSBML in https://github.com/easybuilders/easybuild-easyconfigs/pull/19488

**Comment by smoors** [comment]
this will require fixing `Brunsli` easyconfigs due to `lib*` wildcard:
```
postinstallcmds = [ 
    "mkdir %(installdir)s/bin",
    "cp dbrunsli %(installdir)s/bin/",
    "cp libbrunsli*.a %(installdir)s/lib*/",
    "cp libbrunsli*.%s %%(installdir)s/lib*/" % SHLIB_EXT,
]
```

**Comment by boegel** [comment]
@ocaisa This is a "breaking" change, so I'm re-targeting this to EasyBuild 5.0

@smoors You're right... How did you find that particular easyconfig? Any others that may be hit by this?

**Comment by smoors** [comment]
> @smoors You're right... How did you find that particular easyconfig? Any others that may be hit by this?

quick and dirty regex search on `lib*` after `postinstallcmds`. did not see any other issues, but may have missed some.

**Pull request merged**
