### PR TITLE
stop using CentOS 7.9 container in CI, no longer works now GitHub Actions is using node.js 20

### PR DESCRIPTION
**Pull request by boegel**
required because of problems with `actions/checkout` action like:
```
Run actions/checkout@v3
/usr/bin/docker exec  9843bae9dc7921cd7e422ca131698a5a550184ebb22dc5829be136c5d40196bd sh -c "cat /etc/*release | grep ^ID"
/__e/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /__e/node20/bin/node)
```

see also https://github.com/actions/checkout/issues/1809 + https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Flamefire** [comment]
--> https://github.com/easybuilders/easybuild-framework/pull/4574

**Comment by jfgrimm** [comment]
I've merged #4574 for now
Once support for node16 is fully dropped, we can revisit dropping the CentOS 7.9 container from the CI

**Comment by Flamefire** [comment]
IIUC the container is what matters and as they likely won't change the existing container it might never be dropped for this. Let's see.

**Pull request closed without merging**
