### PR TITLE
don't use `FileExistsError` in `mkdir` function (doesn't exist in Python 2.7)

### PR DESCRIPTION
**Pull request by Flamefire**
Follow-up to #4300 which introduced a Python3 class

Fix by introducing a Python2 implementation and using that.

### CODE REVIEW

**Review by boegel — DISMISSED** [review]
lgtm

**Comment by boegel** [comment]
We overlooked this because we stopped running the tests on top of Python 2 in #4267, ugh...

```
ERROR: test_mkdir (__main__.FileToolsTest)
Test mkdir function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/arcanine/scratch/gent/vo/000/gvo00002/vsc40023/easybuild/easybuild-framework/test/framework/filetools.py", line 631, in test_mkdir
    check_mkdir(barfoodir, error="Failed.*No such file or directory")
  File "/arcanine/scratch/gent/vo/000/gvo00002/vsc40023/easybuild/easybuild-framework/test/framework/filetools.py", line 623, in check_mkdir
    self.assertErrorRegex(EasyBuildError, error, ft.mkdir, path, **kwargs)
  File "easybuild/base/testing.py", line 170, in assertErrorRegex
    call(*args, **kwargs)
  File "easybuild/tools/filetools.py", line 1924, in mkdir
    except FileExistsError as err:
NameError: global name 'FileExistsError' is not defined
```

**Comment by Flamefire** [comment]
> @Flamefire Hmm, new test fails:
> 
> ```
> Traceback (most recent call last):
>   File "/tmp/runner/e377429f58b1fec22562d603da05e3480ca0cfff/lib/python3.6/site-packages/test/framework/filetools.py", line 3399, in test_compat_makedirs
>     self.assertErrorRegex(Exception, os.path.basename(name), py2vs3.makedirs, name)
>   File "/tmp/runner/e377429f58b1fec22562d603da05e3480ca0cfff/lib/python3.6/site-packages/easybuild/base/testing.py", line 178, in assertErrorRegex
>     self.assertTrue(regex.search(msg), "Pattern '%s' is found in '%s'" % (regex.pattern, msg))
> AssertionError: None is not true : Pattern 'folder' is found in '17'
> ```
> 
> edit: fixed in [40f9fe7](https://github.com/easybuilders/easybuild-framework/commit/40f9fe761c1810e45ec407c9343647a3283982e8)

Your fix works, thanks! For reference: "17" is `EEXISTS`, strange that the name isn't always included.

**Comment by boegel** [comment]
I've opened #4333 to bring back running the test suite with Python 2.7...

**Pull request merged**
