### PR TITLE
update bootstrap script to support installing EasyBuild v4.0

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@easybuilders/easybuild-framework-maintainers Since this fixes support for bootstrapping EasyBuild v4.0.0 from scratch, I'd like to see this merged ASAP.

There's still a lot of room for improvement in the bootstrap script (like favoring `pip` over `easy_install`, and requiring neither of them since `setup.py install` will work with just standard Python now), but that's for a follow-up PR...

**Comment by boegel** [comment]
@bartoldeman Good catch.

I'd like to take care of that part in a follow-up PR though, since most people will likely still be bootstrapping EasyBuild with Python 2 (since the standard `python` installation is currently still Python 2 afaik)...

**Comment by bartoldeman** [comment]
Still with python2 getting these errors:
```
[[INFO]] installing EasyBuild with 'easy_install --quiet --upgrade --prefix=/tmp/tmpzJTULC/eb_stage1 easybuild'
  File "build/bdist.linux-x86_64/egg/easybuild/tools/py2vs3/py3.py", line 82
    class WrapperBase(object, metaclass=metaclass):
                                       ^
SyntaxError: invalid syntax

```

```
== fetching files...
== FAILED: Installation ended unsuccessfully (build directory: /tmp/tmpzJTULC/EasyBuild/4.0.0/dummy-dummy): build failed (first 300 chars): Couldn't find file vsc-install-0.11.3.tar.gz anywhere, and downloading it didn't work either... Paths attempted (in order): /tmp/tmpzJTULC/e/EasyBuild/vsc-install-0.11.3.tar.gz, /tmp/tmpzJTULC/EasyBuild/vsc-install-0.11.3.tar.gz, /tmp/tmpzJTULC/vsc-install-0.11.3.tar.gz, /tmp/tmpzJTULC/e/EasyBuild/v (took 1 sec)
== Results of the build can be found in the log file(s) /tmp/eb-6GhLjh/easybuild-EasyBuild-4.0.0-20190921.081254.sTnER.log
Traceback (most recent call last):
  File "./bootstrap_eb.py", line 1114, in <module>
    main()
  File "./bootstrap_eb.py", line 916, in main
    stage2(tmpdir, templates, install_path, distribute_egg_dir, sourcepath)
  File "./bootstrap_eb.py", line 779, in stage2
    easybuild_main()
  File "/tmp/tmpzJTULC/eb_stage1/lib/python2.7/site-packages/easybuild_framework-4.0.0-py2.7.egg/easybuild/main.py", line 434, in main
    ecs_with_res = build_and_install_software(ordered_ecs, init_session_state, exit_on_failure=exit_on_failure)
  File "/tmp/tmpzJTULC/eb_stage1/lib/python2.7/site-packages/easybuild_framework-4.0.0-py2.7.egg/easybuild/main.py", line 147, in build_and_install_software
    raise EasyBuildError(test_msg)
easybuild.tools.build_log.EasyBuildError: 'Build of /tmp/tmpzJTULC/EasyBuild-4.0.0.eb failed (err: "build failed (first 300 chars): Couldn\'t find file vsc-install-0.11.3.tar.gz anywhere, and downloading it didn\'t work either... Paths attempted (in order): /tmp/tmpzJTULC/e/EasyBuild/vsc-install-0.11.3.tar.gz, /tmp/tmpzJTULC/EasyBuild/vsc-install-0.11.3.tar.gz, /tmp/tmpzJTULC/vsc-install-0.11.3.tar.gz, /tmp/tmpzJTULC/e/EasyBuild/v")'
```
Strange that it still tries to download that.

**Comment by boegel** [comment]
@bartoldeman OK, thanks for testing, I'll look into that...

**Comment by boegel** [comment]
@bartoldeman Please test again with Python 2?

The `SyntaxError: invalid syntax` will still be there, but you can treat that as a warning for the time being, it's harmless (won't cause problems with the EasyBuild installation you obtain).

**Comment by bartoldeman** [comment]
it installs successfully for me now. It would be useful to add an info note though, if you cannot work around the innocent SyntaxError (or somehow get py2-compatible syntax in py3.py), otherwise you'll get worried users.

**Comment by boegel** [comment]
@bartoldeman Good idea, added in 83ab583. Good to go now?

**Pull request merged**
