### PR TITLE
Travis CI: Start testing on python 3.6 in allow_failures mode

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by ocaisa** [comment]
@cclauss before you go too far with this, are you aware of the 4.x branch that works with Python 3? Python 3 support is scheduled for the next major release

**Comment by ocaisa** [comment]
See https://github.com/easybuilders/easybuild/issues/447 for details

**Comment by cclauss** [comment]
I was not aware.  That was not in the README.

**Comment by ocaisa** [comment]
Sorry about that, we'll make that more explicit somehow next week

**Comment by cclauss** [comment]
New PRs on 4.x...

**Pull request closed without merging**
