### PR TITLE
Fix trying to generate RPATH wrappers for Clang

### PR DESCRIPTION
**Pull request by casparvl**
[This](https://github.com/easybuilders/easybuild-framework/blob/541a645ab9c8e6fc60345e896a0471a2f75f71e8/easybuild/tools/toolchain/toolchain.py#L990) loop is supposed to loop over all compilers for which wrappers need to be created. However, [this line](https://github.com/easybuilders/easybuild-framework/blob/541a645ab9c8e6fc60345e896a0471a2f75f71e8/easybuild/tools/toolchain/toolchain.py#L973) returns (['clang', 'clang++'],[None, None, None]) for the `Clang` toolchain. The subsequent call to `which` happening [here](https://github.com/easybuilders/easybuild-framework/blob/541a645ab9c8e6fc60345e896a0471a2f75f71e8/easybuild/tools/toolchain/toolchain.py#L991) then fails.

This PR fixes that by explicitely checking if `cmd` is `None`. If so, it proceeds to the next loop iteration and doens't try to create an RPATH wrapper for this 'None' command.

### CODE REVIEW

**Comment by boegel** [comment]
@casparvl It would be nice if we could enhance the `test_toolchain_prepare_rpath` test to cover this fix.

Without this change, what happens? A hard crash, or RPATH linking just doesn't happen?

**Comment by casparvl** [comment]
Yes, without this, a `prepare_rpath_wrappers()` call on a `Clang` toolchain will fail (some complaint about a `Nonetype` blabla since it expects a string)

**Comment by casparvl** [comment]
@boegel is this more or less what you had in mind in terms of test? Can you review this PR, in conjuction with this EasyBlock PR https://github.com/easybuilders/easybuild-easyblocks/pull/2799 ?

**Comment by boegel** [comment]
@casparvl That test is perfect: if I run it after temporarily undoing the fix in `easybuild/tools/toolchain/toolchain.py`, then it reproduces the problem being fixed:

```
ERROR: test_toolchain_prepare_rpath (test.framework.toolchain.ToolchainTest)
Test toolchain.prepare under --rpath
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Volumes/work/easybuild-framework/test/framework/toolchain.py", line 2627, in test_toolchain_prepare_rpath
    tc_clang.prepare_rpath_wrappers()
  File "/Volumes/work/easybuild-framework/easybuild/tools/toolchain/toolchain.py", line 994, in prepare_rpath_wrappers
    orig_cmd = which(cmd)
  File "/Volumes/work/easybuild-framework/easybuild/tools/filetools.py", line 521, in which
    cmd_path = os.path.join(path, cmd)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
```

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
