### PR TITLE
replaced distutils LooseVersion with packaging.version.parse

### LINKED ISSUE #4072: [bug|feature] Fixing version parsing of easyconfigs in `tweak.py`
### Context
I am running eb/4.6.0, and I was trying to update [OpenCV-4.5.5-foss-2021b-contrib.eb](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/o/OpenCV/OpenCV-4.5.5-foss-2021b-contrib.eb) to `v4.6.0` on `foss/2022a` with updated deps, i.e.:
 ```
eb OpenCV-4.5.5-foss-2021b-contrib.eb --try-software-version=4.6.0 --try-toolchain-version=2022a --try-update-deps -Dr
```
But I quickly run into the following error:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/sw/noarch/Centos8/2021/software/EasyBuild/4.6.0/lib/python3.6/site-packages/easybuild/main.py", line 597, in <module>
    main()
  File "/sw/noarch/Centos8/2021/software/EasyBuild/4.6.0/lib/python3.6/site-packages/easybuild/main.py", line 440, in main
    easyconfigs = tweak(easyconfigs, build_specs, modtool, targetdirs=tweaked_ecs_paths)
  File "/sw/noarch/Centos8/2021/software/EasyBuild/4.6.0/lib/python3.6/site-packages/easybuild/framework/easyconfig/tweak.py", line 203, in tweak
    ignore_versionsuffixes=ignore_versionsuffixes)
  File "/sw/noarch/Centos8/2021/software/EasyBuild/4.6.0/lib/python3.6/site-packages/easybuild/framework/easyconfig/tweak.py", line 1064, in map_easyconfig_to_target_tc_hierarchy
    ignore_versionsuffixes=ignore_versionsuffixes
  File "/sw/noarch/Centos8/2021/software/EasyBuild/4.6.0/lib/python3.6/site-packages/easybuild/framework/easyconfig/tweak.py", line 1223, in find_potential_version_mappings
    LooseVersion(version) > LooseVersion(highest_version_ignoring_versionsuffix):
  File "/usr/lib64/python3.6/distutils/version.py", line 64, in __gt__
    c = self._cmp(other)
  File "/usr/lib64/python3.6/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'int' and 'str'
```
I'm clearly not the first/only one who ran into this issue: #3996 

As I will show, the reason for the above error is two-fold:
1. EasyConfig (ec) version string substitution doesn't work in the regex which is used to retrieve the software version in `tweak.py`.
1. Correctly substituted strings still are not comparable 

### Issue 1. 
For a few ec's, version string substitution is used, e.g. [Java-1.8.0_292-OpenJDK.eb](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/j/Java/Java-1.8.0_292-OpenJDK.eb).
The problem is that the un-substituted version string is obtained from `fetch_parameters_from_easyconfig`, which simply regex-es the ec for the version.
https://github.com/easybuilders/easybuild-framework/blob/b6daaacf08ac0b6ebec6c191f4359e2dcbfff5a0/easybuild/framework/easyconfig/tweak.py#L1213-L1214
For the above `Java-1.8.0_292-OpenJDK.eb`, the obtained version is:
`"'1.%s.0_%s' % (local_java_version, local_patch_version)"`

#### Proposed fix:
We could replace this function call with calling `process_easyconfig`, which actually does perform substitution:
```
# Replace the below:
# version, newversionsuffix = fetch_parameters_from_easyconfig(read_file(path), ['versionsuffix'])
#
ec = process_easyconfig(path)[0]['ec']
version, newversionsuffix = (
    ec.get('version', None),
    ec.get('versionsuffix', None)
)
```

- distutils is deprecated
  - https://peps.python.org/pep-0440/
  - packaging 20.9 for python == 2.7, 3.5
  - packaging 21.3 is the latest release

```python
$ python
Python 3.10.4 (main, Jul 13 2022, 12:16:05) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from distutils.version import LooseVersion
>>> from packaging.version import parse
>>> 
>>> v1, v2 = "Java-1.8_265", "Java-1.8.0_292"
>>>
>>> LooseVersion(v1) < LooseVersion(v2)
<stdin>:1: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robertsc/.local/easybuild/Centos8/2021/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/site-packages/setuptools/_distutils/version.py", line 72, in __lt__
    c = self._cmp(other)
  File "/home/robertsc/.local/easybuild/Centos8/2021/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/site-packages/setuptools/_distutils/version.py", line 357, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
>>>
>>> parse(v1) < parse(v2)
True
>>> 
```

Roadblocks:
- Requires an new python dependency (`packaging`, which is included in `setuptools`)

[Python/3.10.4-GCCcore-11.3.0](https://github.com/easybuilders/easybuild-framework/issues/3996)

### PR DESCRIPTION
**Pull request by robogast**
Fixes #4072, and #3996 partially.

This is my first PR for easybuild-framework, help is appreciated :)

### CODE REVIEW

**Comment by Flamefire** [comment]
Adding an extra requirement is quite a lot to ask. I implemented a simple copy of `LooseVersion` in #3794 and is purposely simple.

And I mean from #4072

> comparing Java-1.8_265-b01 to Java-1.8.0_292, i.e. 1.8_265 to 1.8.0_292

What does it really mean to compare `1.8_265` to `1.8.0_292`? Without someone checking those shouldn't be (easily) comparable so an error in this case is good IMO.

**Comment by robogast** [comment]
The pros/cons for the two ways of resolving the version comparison problem (feel free in adding/subtracting pros/cons from both lists, the following is just my opinion)
### `packaging.version.parse`:
#### Pros:
- Explicitly adheres to Python's extensive and well defined versioning scheme ([PEP-0440](https://peps.python.org/pep-0440/))
- Available for all Python versions (including 2.7)
- Is the advised way of replacing `disutils.version.LooseVersion` ([PEP-0632](https://peps.python.org/pep-0632/#migration-advice))
  - `packaging` is already included in `setuptools`
  - `distutils` (which is used in e.g. [`setup.py`](https://github.com/easybuilders/easybuild-framework/blob/develop/setup.py)) is deprecated and needs to be replaced by `setuptools` anyway by Python 3.12
  - PEP-0632 is also linked in the thread from which @Flamefire takes the fix for LooseVersion's str/int comparison issue #3996.

#### Cons:
- Adds a requirement
- Makes a (possibly wrong) decision in ambiguous cases such as comparing Java-1.8_265-b01 to Java-1.8.0_292, i.e. 1.8_265 to 1.8.0_292

### `easybuild-framework.tools.LooseVersion`
#### Pros:
- No additional requirement
- "Simple" implementation
#### Cons:
- Doesn't adhere to any standard(ized) versioning scheme
- Re-invents the wheel
- Doesn't handle complex cases (automatically)

I understand why the ambiguous case of comparing `1.8_265` to `1.8.0_292` is unfortunate, but breaking tools such as `tweak.py` in favor of manual decision making is (in my opinion) not a solution.

**Comment by Micket** [comment]
We need to also consider the easyblocks and the many many places they use LooseVersion (and not only the ones we have, but also whatever people are using outside of the main repo). SI suspect noone is volunteering to changing all of those to parse and checking that nothing broke, so a switch to parse is something i think we have to introduce gradually there, and we regardless need to provide the easybuild-framework.tools.LooseVersion during that transition.

**Comment by boegel** [comment]
My 2 cents on this: while it seems like we may not be able to avoid a dependency on `setuptools` from Python 3.12 onwards (to be checked, I still hope we can avoid that since we know it's going to be a PITA if not), my preference goes to "vendoring" `LooseVersion` as is done in #3794.

Not only does it avoid introducing a dependency on a Python package outside the standard library, but it also means that nothing really changes, so there won't be surprises with version checking suddenly being done slightly differently.

We have a broad set of test cases in the easyconfigs repository that we can test with, there are other interesting cases like OpenFOAM, LAMMPS, etc. which we should also check.

That said, I think whatever road we take, this is EasyBuild 5.0 material, since the potential impact is not small (and Python 3.12 is not available yet).

**Comment by Flamefire** [comment]
> That said, I think whatever road we take, this is EasyBuild 5.0 material, since the potential impact is not small (and Python 3.12 is not available yet).

I don't see how #3794 is a breaking change. It is a more or less 1:1 copy of the existing LooseVersion with a corner case fixed which didn't work before simplifying code that wants to use it. I would suggest to merge that and transition to it soon so that we can test it extensively before the next release.

**Comment by boegel** [comment]
> > That said, I think whatever road we take, this is EasyBuild 5.0 material, since the potential impact is not small (and Python 3.12 is not available yet).
> 
> I don't see how #3794 is a breaking change. It is a more or less 1:1 copy of the existing LooseVersion with a corner case fixed which didn't work before simplifying code that wants to use it. I would suggest to merge that and transition to it soon so that we can test it extensively before the next release.

I didn't call #3794 a breaking change, but it definitely is an intrusive one.
In theory, it's the same code (except, it's not really, since there's a bugfix on top).

We've discussed #3794 briefly during the EasyBuild conf call (again) today, and the general consensus is that we should just go ahead with it (without waiting for EasyBuild v5.0).

**Comment by boegel** [comment]
Closing this since #3794 has been merged

**Pull request closed without merging**
