### PR TITLE
Pin GitPython version for Python<3.6, don't test bootstrap script against Python 3.8/3.9

### PR DESCRIPTION
**Pull request by ocaisa**

### CODE REVIEW

**Comment by ocaisa** [comment]
@boegel Now the unit tests but the bootstrap is failing 😢

**Comment by ocaisa** [comment]
Version bumps in Python 3.8 and 3.9 since yesterday that are causing the failures

**Comment by ocaisa** [comment]
```
Warning
Easy Install is deprecated. Do not use it. Instead use pip. If you think you need Easy Install, please reach out to the PyPA team (a ticket to pip or setuptools is fine), describing your use-case.
```

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
