### PR TITLE
add 'parallel' to list of config templates

### PR DESCRIPTION
**Pull request by migueldiascosta**
answers #2929?

### CODE REVIEW

**Comment by boegel** [comment]
@migueldiascosta Wait, does `%(parallel)s` actually ever get resolved when used in an easyconfig file?

**Comment by migueldiascosta** [comment]
@boegel with this change, yes... (just tried it again)

**Comment by boegel** [comment]
@migueldiascosta OK, but then we should get that properly covered in the tests too...

The non-`None` value for `parallel` is only available after a certain step (`ready`), see `set_parallel` in `easyblock.py`.

Done in https://github.com/migueldiascosta/easybuild-framework/pull/9

**Comment by boegel** [comment]
Thanks @migueldiascosta!

**Pull request merged**
