### PR TITLE
fix crash in create_test_report with --upload-test-report --from-pr when one or more test installations failed

### PR DESCRIPTION
**Pull request by Flamefire**
PR numbers are integers which cannot be joined to a string directly but need to be converted first

Introduced by https://github.com/easybuilders/easybuild-framework/pull/3605

Error:
```
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/h3/s3248973/.local/EasyBuildDev/easybuild-framework/easybuild/main.py", line 548, in <module>
    main()
  File "/home/h3/s3248973/.local/EasyBuildDev/easybuild-framework/easybuild/main.py", line 527, in main
    test_report_msg = overall_test_report(ecs_with_res, len(paths), overall_success, success_msg, init_session_state)
  File "/home/s3248973/.local/EasyBuildDev/easybuild-framework/easybuild/tools/testing.py", line 351, in overall_test_report
    easyblock_pr_nrs=easyblock_pr_nrs)
  File "/home/s3248973/.local/EasyBuildDev/easybuild-framework/easybuild/tools/testing.py", line 196, in create_test_report
    descr += " (PR #%s)" % ', #'.join(pr_nrs)
TypeError: sequence item 0: expected string, int found
```

### CODE REVIEW

**Review by akesandgren — DISMISSED** [review]
LGTM

**Comment by boegel** [comment]
I squeezed in a test that triggers the fixed bug.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
