### PR TITLE
allow deprecated behaviour when running `test_fetch_sources_git` with Python < 3.9

### PR DESCRIPTION
**Pull request by branfosj**
From https://github.com/easybuilders/easybuild-framework/actions/runs/12544709924/job/34977742103

```
======================================================================
ERROR: test_fetch_sources_git (test.framework.easyblock.EasyBlockTest)
Test fetch_sources method from git repo.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/runner/e361bb6a84c200b516a56bf3a0355d38d85acace/lib/python3.7/site-packages/test/framework/easyblock.py", line 1718, in test_fetch_sources_git
    eb.fetch_sources(sources, checksums=checksums)
  File "/tmp/runner/e361bb6a84c200b516a56bf3a0355d38d85acace/lib/python3.7/site-packages/easybuild/framework/easyblock.py", line 511, in fetch_sources
    checksum = self.get_checksum_for(checksums=checksums, filename=source, index=index)
  File "/tmp/runner/e361bb6a84c200b516a56bf3a0355d38d85acace/lib/python3.7/site-packages/easybuild/framework/easyblock.py", line 387, in get_checksum_for
    '6.0'
  File "/tmp/runner/e361bb6a84c200b516a56bf3a0355d38d85acace/lib/python3.7/site-packages/easybuild/tools/build_log.py", line 215, in deprecated
    fancylogger.FancyLogger.deprecated(self, msg, str(CURRENT_VERSION), ver, *args, **kwargs)
  File "/tmp/runner/e361bb6a84c200b516a56bf3a0355d38d85acace/lib/python3.7/site-packages/easybuild/base/fancylogger.py", line 346, in deprecated
    self.raiseException("DEPRECATED (since v%s) functionality used: %s" % (max_ver, msg), exception=exception)
  File "/tmp/runner/e361bb6a84c200b516a56bf3a0355d38d85acace/lib/python3.7/site-packages/easybuild/base/fancylogger.py", line 330, in raiseException
    raise exception(message).with_traceback(tb)
easybuild.tools.build_log.EasyBuildError: 'DEPRECATED (since v6.0) functionality used: Reproducible tarballs of Git repos are only possible when using Python 3.9+ to run EasyBuild. Skipping checksum verification of testrepository.tar.xz since Python < 3.9 is used.; see https://docs.easybuild.io/deprecated-functionality/ for more information'
```

### CODE REVIEW

**Review by Micket — DISMISSED** [review]
lgtm

**Comment by Micket** [comment]
Alternatively, we should run the test while allowing deprecated functionality?

**Comment by branfosj** [comment]
> Alternatively, we should run the test while allowing deprecated functionality?

I've relooked at the test and I'll fix it to test both the deprecated and standard workflow.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
