### PR TITLE
mark easystack support as being mature, since it's no longer experimental

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
I really want to mark easystack support as non-experimental in EasyBuild 5.0, so I think we should already go ahead and merge this even without having #4667 merged (since that's just an enhancement)

**Comment by ocaisa** [comment]
#4667 is ready to merge IMHO, it includes tests. If we make easystack support stable then that PR would introduce an unintended regression

**Comment by boegel** [comment]
> #4667 is ready to merge IMHO, it includes tests. If we make easystack support stable then that PR would introduce an unintended regression

@ocaisa You're right, I've merged #4667, so I think this is good to go too (the changes in #4667 will be collapsed into `5.0.x` branch, or the other way around, soon)

**Review by ocaisa — APPROVED** [review]

**Pull request merged**
