### PR TITLE
don't clean up imported modules after verifying imports of included Python modules

### LINKED ISSUE #3542: Occasional failures with Python 2, triggered by cleanup of imported modules in verify_imports
When using EasyBuild with Python 2, I'm experiencing occasional failures with a traceback like this:
```
[...]
  File ".../easybuild/framework/easyconfig/easyconfig.py", line 2537, in det_full_module_name
    require_result=require_result)
  File ".../easybuild/framework/easyconfig/easyconfig.py", line 2509, in _det_module_name_with
    mod_name = mns_method(ec)
  File ".../easybuild/tools/module_naming_scheme/hierarchical_mns.py", line 89, in det_full_module_name
    return os.path.join(self.det_module_subdir(ec), self.det_short_module_name(ec))
AttributeError: 'NoneType' object has no attribute 'path'
```
The exact circumstances still seem to be unclear, but according to @Flamefire it may be related to https://stackoverflow.com/questions/29107470/imported-modules-becomes-none-when-replacing-current-module-in-sys-modules-using

### PR DESCRIPTION
**Pull request by boegel**
fixes #3542

### CODE REVIEW

**Comment by ocaisa** [comment]
@Flamefire This looks ok to me since the `clear()` and `update()` are only being done in the tests, so we shouldn't run into these runtime issues any more. I don't trust that I fully understand the issue though, can you review this PR?

**Comment by Flamefire** [comment]
I have found https://stackoverflow.com/questions/43181440/what-does-del-sys-modulesmodule-actually-do which references the python docs:

> [`sys.modules`] is a dictionary that maps module names to modules which have already been loaded. This can be manipulated to force reloading of modules and other tricks. However, replacing the dictionary will not necessarily work as expected and deleting essential items from the dictionary may cause Python to fail.

So IMO even though it is test code this shouldn't be done as it seems to be unreliable (as shown by the issue: adding an extra import seems to have triggered the GC causing the issue to become a bug).
Why was the test code changed? Wasn't the old stuff (`del` and `reload`) enough?

I assume the `del` to be fine, so the module code change is good as far as I can tell, thanks!

**Comment by boegel** [comment]
I added the `sys.modules.clear()` in the test at some point because it seemed necessary, but it actually isn't, the `del sys.modules[*]` statements indeed work just as well; fixed in 98578934b .

**Review by ocaisa — APPROVED** [review]
LGTM

**Review by Flamefire — APPROVED** [review]

**Pull request merged**
