### PR TITLE
Use print() function in both Python 2 and Python 3

### PR DESCRIPTION
**Pull request by cclauss**
Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.

### CODE REVIEW

**Comment by boegel** [comment]
@cclauss Thank you very much for your contribution!

I appreciate your effort, but the `port_easyblock.py` script is of little use now, so there's little point it making changes to it...
It was added to the repository a long time ago to help early adopters of EasyBuild to migrate to the (I believe) EasyBuild v1.0 stable release.

This script of no use anymore, so it should just be removed for the upcoming EasyBuild v4.0 release, together with a couple of other scripts located in the same directory. I'll take care of that in a separate PR.

The code we do still care about has already been updated  in the `4.x` branch to support both Python 2.x (2.6 or 2.7) and Python 3.x (3.5 or newer). We aim to release EasyBuild 4.0 from this branch sometime in the coming weeks/months (ETA is summer 2019).

**Comment by cclauss** [comment]
Should we close this PR?

**Comment by boegel** [comment]
Eventually, yes, but let’s keep it open for now to serve as a reminder for me to clean up those old scripts...

**Comment by boegel** [comment]
`port_easyblock.py` script removed in #2897

**Pull request closed without merging**
