### PR TITLE
add support for using --output-format=md (MarkDown)

### PR DESCRIPTION
**Pull request by boegel**
* [x] `eb --avail-cfgfile-constants --output-format md`
* [x] `eb --avail-easyconfig-constants --output-format md`
* [x] `eb --avail-easyconfig-licenses --output-format md`
* [x] `eb --avail-easyconfig-params --output-format md`
* [x] `eb --avail-easyconfig-templates --output-format md`
* [x] `eb --avail-toolchain-opts ... --output-format md`
* [x] `eb --list-easyblocks --output-format md`
* [x] `eb --list-software --output-format md`
* [x] `eb --list-toolchains --output-format md`
* [x] `eb --help-md`
* [x] `gen_easyblocks_overview_md`

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegel is this a blocker for 4.7.0?

**Comment by boegel** [comment]
> @boegel is this a blocker for 4.7.0?

To me, yes, I really want this finished and merged before releasing EasyBuild v4.7.0...

I'll have time to finish it this week (working on it right now).

**Review by branfosj — CHANGES_REQUESTED** [review]
I _think_ this is the right syntax to get rid of most of the problems in the https://github.com/easybuilders/easybuild-docs/actions/runs/3836711232/jobs/6531176502 without changing the internal links.

**Review by branfosj — APPROVED** [review]
We'll put the suggested changes into a future PR

**Comment by branfosj** [comment]
> This seemingly broke the test suite with the type "developement"

Yes, in combination with #4154

There is a fix in #4155

**Pull request merged**
