### PR TITLE
indicate compatibility with Python 3.10 in setup.py

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by migueldiascosta** [comment]
lgtm w.r.t. python 3.10, but is github still confused about #3939? that commit is definitely already in develop...

**Comment by boegel** [comment]
@migueldiascosta Confusion resolved by syncing with current `develop`

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Pull request merged**
