### PR TITLE
Error out if some GC3Pie job failed.

### PR DESCRIPTION
**Pull request by riccardomurri**
As requested by Will Furnass on the EB chat:
https://easybuild.slack.com/archives/C34UA1HT7/p1570098913442400

### CODE REVIEW

**Comment by boegel** [comment]
@riccardomurri I'd like to enhance the existing test we have for using GC3Pie as a backend, to verify that a failing build indeed results in a raised error (and that it stays that way).

I started looking into this myself, but noticed that `test_build_easyconfigs_in_parallel_gc3pie` basically hangs on my system (macOS) for some reason (it works fine in Travis CI & GitHub Actions though), which makes that very annoying to work on. :)

I'd like to pick your brain on that... Can you think of something that could be causing that, from the top of your head (some different behavior between macOS & Linux would be my first guess)?

**Comment by riccardomurri** [comment]
Added report of names of jobs that failed, as further requested by Will on chat.

**Comment by riccardomurri** [comment]
> I started looking into this myself, but noticed that test_build_easyconfigs_in_parallel_gc3pie basically hangs on my system (macOS)

@boegel Maybe this should be posted as a bug on GC3Pie?  If you Ctrl+C that script while it hangs, what traceback do you get?

**Comment by riccardomurri** [comment]
> Can you think of something that could be causing that, from the top of your head (some different behavior between macOS & Linux would be my first guess)?

If you have GC3Pie configured to use the `shellcmd` ("localhost") backend, then it may hang while running some local discovery command... Maybe Apple has changed something in the latest releases, or some command has a hidden resource deadlock that causes it to break when run in parallel...

**Pull request merged**
