### PR TITLE
Fixing a bug in which filtered dependencies based on complex filterin…

### PR DESCRIPTION
**Pull request by mboisson**
…g schema (specific versions) were not being filtered.

I moved much of the filter_deps code to "dep_is_filtered" function, and reuse that function in _finalize_dependencies, which was only checking for the name of the dependency, instead of the full version check.

### CODE REVIEW

**Comment by boegel** [comment]
This definitely needs a test before it gets merged (or we *will* be bitten by this again sooner or later).

**Comment by boegel** [comment]
@mboisson How did the bug manifest itself exactly? Was it via an error like `Failed to determine minimal toolchain for dep`?

**Comment by bartoldeman** [comment]
Reopening to see if mysterious py 3.5 failure is reproduced.

**Comment by bartoldeman** [comment]
@mboisson I merged your branch with develop to see because it was a little out of sync with the Py3 changes. On build-node the tests run ok:
```
[oldeman@build-node easybuild-framework]$ module load python/3.5.4
[oldeman@build-node easybuild-framework]$ export PYTHONPATH=$HOME/easybuild-framework:$HOME/easybuild-easyblock

[oldeman@build-node easybuild-framework]$ python -O -m test.framework.options filter
Filtered CommandLineOptionsTest tests using 'filter', retained 2/91 tests: test_filter_deps, test_test_report_env_filter
..
----------------------------------------------------------------------
Ran 2 tests in 12.707s

OK
[oldeman@build-node easybuild-framework]$ which python
/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.5.4/bin/python
[oldeman@build-node easybuild-framework]$ module load python/3.6.3

The following have been reloaded with a version change:
  1) python/3.5.4 => python/3.6.3

[oldeman@build-node easybuild-framework]$ python -O -m test.framework.options filter
Filtered CommandLineOptionsTest tests using 'filter', retained 2/91 tests: test_filter_deps, test_test_report_env_filter
..
----------------------------------------------------------------------
Ran 2 tests in 13.263s

OK
[oldeman@build-node easybuild-framework]$ module load python/3.7.4

The following have been reloaded with a version change:
  1) python/3.6.3 => python/3.7.4

[oldeman@build-node easybuild-framework]$ python -O -m test.framework.options filter
Filtered CommandLineOptionsTest tests using 'filter', retained 2/91 tests: test_filter_deps, test_test_report_env_filter
..
----------------------------------------------------------------------
Ran 2 tests in 12.938s

OK
```
Let's hope travis is happy with them too.
(EB 4.0 dropped the vsc dependency so it now runs with our plain Python modules, except for some optional stuff).

**Comment by bartoldeman** [comment]
Trying once more...

**Comment by boegel** [comment]
@bartoldeman If a test frequently fails for no good reason with Python 3.5, we should try and get to the bottom of it, not re-trigger the tests until it passes. ;)

Is this the same test that was failing for your PR #2994, i.e. `test_toy_build_formatv2` in https://travis-ci.org/easybuilders/easybuild-framework/jobs/581824226?

**Pull request merged**
