### PR TITLE
Use version suffixes in PR title instead of Python versions when using --new-pr 

### PR DESCRIPTION
**Pull request by Micket**
Has bothered me for a while now. the w/ Python 3.x.y in the titles are pretty much useless these days, and instead important information like if a CUDA build is left out. 
This puts all the suffixes in there instead.

### CODE REVIEW

**Comment by boegel** [comment]
@Micket Can you clarify why this is marked as draft?

**Comment by Micket** [comment]
I never got around to test any of the code at all. Might work, 100% untested

**Comment by Micket** [comment]
I think this works fine
```
$ eb --new-pr GATK-4.1.3.0-GCCcore-8.2.0-Java-1.8.eb -D  testing-1.2.3-foss-2022a-CUDA-11.7.0.eb 
== Temporary log file in case of crash /dev/shm/eb-5xcxca2p/easybuild-ugshj3o6.log
== fetching branch 'develop' from https://github.com/easybuilders/easybuild-easyconfigs.git...
== copying files to /dev/shm/eb-5xcxca2p/git-working-diryxxzy5g1/easybuild-easyconfigs...
== pushing branch '20230529154625_new_pr_GATK4130' to remote 'github_Micket_zMHdd' (git@github.com:Micket/easybuild-easyconfigs.git) [DRY RUN]

Opening pull request [DRY RUN]
* target: easybuilders/easybuild-easyconfigs:develop
* from: Micket/easybuild-easyconfigs:20230529154625_new_pr_GATK4130
* title: "{bio,devel}[GCCcore/8.2.0,foss/2022a] GATK v4.1.3.0, testing v1.2.3 w/ CUDA 11.7.0, Java 1.8"
* labels: new, update
* description:
"""
```
when testing with a few random easyconfigs

**Comment by branfosj** [comment]
So the test for this whole new PR function is at https://github.com/easybuilders/easybuild-framework/blob/f378bac46cc85c9fcdaf7649da28f7e3d1c37f0b/test/framework/options.py#L4177, which neither tests multiple easyconfigs or anything with a versionsuffix.

I do think we should pull this code out into a separate function and test it separately. Then, in an outside the scope of this PR, we'd be able to hook it into the review PR code to have it suggest a PR title should be.

**Comment by Micket** [comment]
I'm not sure how to best set up tests for this. It's isolated to just the `ecs` variable but still quite a hassle to fake those.

**Comment by branfosj** [comment]
> I'm not sure how to best set up tests for this. It's isolated to just the `ecs` variable but still quite a hassle to fake those.

See https://github.com/Micket/easybuild-framework/pull/2

**Comment by branfosj** [comment]
Also, if there are any other unusual software names / versions / versionsuffixes we should test then let me know and I'll add some more.

**Review by branfosj — APPROVED** [review]

**Pull request merged**
