### PR TITLE
consider $EB_INSTALLPYTHON to specify 'python' command to use for running EasyBuild

### PR DESCRIPTION
**Pull request by ocaisa**
Replaces #3394 (which was created on a branch in the easybuilders repo by accident)

This replaces the use of the `EB_PYTHON` in an EasyBuild module (generated by EasyBuild). `EB_PYTHON` still takes precedence

### CODE REVIEW

**Comment by migueldiascosta** [comment]
according to the comments in https://github.com/easybuilders/easybuild-framework/pull/3394 and https://github.com/easybuilders/easybuild-easyblocks/issues/2078#issuecomment-669009467, this solution is not consensual yet?

Or are the clarifications in the eb script sufficient now?

**Comment by akesandgren** [comment]
This is clearly the best solution for the problem at hand in my opinion.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Won't merge though until I get the go-ahead from @boegel

**Comment by boegel** [comment]
Makes sense, the clarifying comment clearly explains why we consider two environment variables now. :+1:

**Comment by ocaisa** [comment]
Thanks @akesandgren don't forget to also review/merge https://github.com/easybuilders/easybuild-easyblocks/pull/2109 or this won't do much!

**Pull request merged**
