### PR TITLE
Also dump environment to reprod directory

### LINKED ISSUE #2111: RFF: dump a copy of --dump-env-script output in the %(installdir)/easybuild directory as an .env file for each build
I think the Subject: covers it.

But if it doesn't...... sometimes its nice to have a quick reference (especially for users) of what the environment was like when a certain package was built.  Especially if they want to use the EB version to build a custom version.  %(installdir)/easybuild already has a -devel file but its basically useless for users.  And teaching users how to use EB and run --dump-env-script is a bit much.   So lets just make a "easy build" copy for them.

More beer rewards available though given the picture boegel sent me of the beer stocks purchased for the EasyBuild user meeting, I imagine most of those at the hackathon on Friday will be drowning already.  Goodness gracious.   If y'all (those listed as being there) drink all of that, I'm going to have to work on your next trip to SC in Austin.

### PR DESCRIPTION
**Pull request by ocaisa**
fixes #2111, related to #2284 (but doesn't really fixes it, according to @boegel)

### CODE REVIEW

**Comment by ocaisa** [comment]
Urgh, this triggers new logging which is breaking some tests that don't expect it.

**Comment by boegel** [comment]
@ocaisa So you should fix up those tests then?

**Comment by ocaisa** [comment]
@boegel I need some advice on this one, placing the env dump in the reprod dir saves me from having to do any bookkeeping but because it creates a nested easyblock instance there is a bit of a logging mess that is kicking errors in the tests

**Review by boegel — DISMISSED** [review]
@ocaisa The env script is dumped too early, the build environment isn't set up yet when you create it:

```
$ cat $EASYBUILD_PREFIX/software/bzip2/1.0.8-GCCcore-9.3.0/easybuild/reprod/*env
#!/bin/bash
# script to set up build environment as defined by EasyBuild v4.2.2.dev0 for bzip2-1.0.8-GCCcore-9.3.0.eb
# usage: source bzip2-1.0.8-GCCcore-9.3.0.env

# toolchain & dependency modules
# (no modules loaded)

# build environment
# (no build environment defined)
```

**Comment by ocaisa** [comment]
@boegel I switched it to be done after the easyblock has been used and it seems to work. I haven't capture that in the tests though yet. 

This is not foolproof I suspect since it doesn't handle multi-deps or iterating builds

**Comment by ocaisa** [comment]
@boegel I've added an additonal test that at least captures the module load for a dependency. Is it possible to trigger a build environment variable in the tests?

I've also addressed the comment you made in https://github.com/easybuilders/easybuild-framework/pull/3375#discussion_r449758849

**Comment by boegel** [comment]
> @boegel I've added an additonal test that at least captures the module load for a dependency. Is it possible to trigger a build environment variable in the tests?

@ocaisa What do you mean by "build environment variable"?

To change the EasyBuild configuration used in a test, you can use `init_config`.
To define one or more environment variables, just use `os.environ` or `setvar` from `easybuild.tools.environment`

**Comment by ocaisa** [comment]
Hard to remember, but I think I was talking about populating the lines
```
# build environment
# (no build environment defined)
```
such as `CC`, `CXX` etc.

**Comment by ocaisa** [comment]
@boegel I'm kicking the tyres on this because it is actually really useful to have for EESSI, for example if someone wants build their own custom version of a package (I'm thinking about application maintainers using it in CI)

**Comment by akesandgren** [comment]
@ocaisa  This looks sane to me.
Is it finished and ready for merging?
@boegel any remaining issues from your side?

**Comment by ocaisa** [comment]
I think it works fine, there is potentially an issue with multideps but we don't really have those any more.

Example:
```
[ocaisa@login1 easybuild-framework]$ eb OSU-Micro-Benchmarks-5.7.1-gompi-2021b.eb --force
...
[ocaisa@login1 easybuild-framework]$ cat /home/ocaisa/.local/easybuild/software/OSU-Micro-Benchmarks/5.7.1-gompi-2021b/easybuild/reprod/OSU-Micro-Benchmarks-5.7.1-gompi-2021b.env
#!/bin/bash
# script to set up build environment as defined by EasyBuild v4.4.3.dev0 for OSU-Micro-Benchmarks-5.7.1-gompi-2021b.eb
# usage: source OSU-Micro-Benchmarks-5.7.1-gompi-2021b.env

# toolchain & dependency modules
module load gompi/2021b

# build environment
export CC='mpicc'
export CC_SEQ='gcc'
export CFLAGS='-O2 -ftree-vectorize -march=native -fno-math-errno'
export CXX='mpicxx'
export CXXFLAGS='-O2 -ftree-vectorize -march=native -fno-math-errno'
export CXX_SEQ='g++'
export F77='mpifort'
export F77_SEQ='gfortran'
export F90='mpifort'
export F90FLAGS='-O2 -ftree-vectorize -march=native -fno-math-errno'
export F90_SEQ='gfortran'
export FC='mpifort'
export FCFLAGS='-O2 -ftree-vectorize -march=native -fno-math-errno'
export FC_SEQ='gfortran'
export FFLAGS='-O2 -ftree-vectorize -march=native -fno-math-errno'
export FLIBS='-lgfortran'
export LDFLAGS='-L/project/boegelbot/Rocky8/haswell/software/GCCcore/11.2.0/lib64 -L/project/boegelbot/Rocky8/haswell/software/GCCcore/11.2.0/lib'
export LIBS='-lm -lpthread'
export MPICC='mpicc'
export MPICXX='mpicxx'
export MPIF77='mpifort'
export MPIF90='mpifort'
export MPIFC='mpifort'
export MPI_INC_DIR='/project/boegelbot/Rocky8/haswell/software/OpenMPI/4.1.1-GCC-11.2.0/include'
export MPI_LIB_DIR='/project/boegelbot/Rocky8/haswell/software/OpenMPI/4.1.1-GCC-11.2.0/lib64'
export MPI_LIB_SHARED='/project/boegelbot/Rocky8/haswell/software/OpenMPI/4.1.1-GCC-11.2.0/lib64/libmpi.so'
export MPI_LIB_STATIC=''
export OMPI_CC='gcc'
export OMPI_CXX='g++'
export OMPI_F77='gfortran'
export OMPI_F90='gfortran'
export OMPI_FC='gfortran'
export OPTFLAGS='-O2 -ftree-vectorize -march=native'
export PRECFLAGS='-fno-math-errno'
```

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @ocaisa!

**Pull request merged**
