### PR TITLE
change semantics of `--dry-run`, so it doesn't imply `--robot`

### PR DESCRIPTION
**Pull request by smoors**
`--dry-run` without `--robot` should only show info about the easyconfig itself, not the dependencies.

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm i guess, have we discussed this change?

**Comment by boegel** [comment]
Hmm, muscle memory is strong for me for using `-D` and getting full overview of what's needed, but typing an extra `r` isn't too bad, so I don't mind.

I guess we should check with maintainers if anyone else strongly objects, but I can live with it.

@smoors I do wonder what motivated you to look into this...

**Comment by smoors** [comment]
consistency! :)

this is useful when working with an easystack file, and you want to check for each easyconfig in the easystack if it has been installed and get the corresponding module name. you can of course do a grep on the output, but it’s a bit cumbersome.

it runs also much faster without the dependencies.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by Micket** [comment]
Everyone is on board. Merging

**Pull request merged**
