### PR TITLE
fix default target GitHub account/organisation for --new-pr & co + fix tests that got broken by migration to github.com/easybuilders

### PR DESCRIPTION
**Pull request by boegel**
fix for #2257

### CODE REVIEW

**Comment by boegel** [comment]
@easybuilders/easybuild-framework-maintainers Green light by Travis, this is blocking several other PRs, please review.

**Comment by damianam** [comment]
lgtm. I'd merge it, but I don't have the rights yet :-/

**Comment by boegel** [comment]
@damianam OK, that's strange, I've assigned your write permissions, both individually and via the `easybuild-framework maintainers` team... :-/

**Comment by boegel** [comment]
@damianam image

**Comment by ocaisa** [comment]
I have the power!....trusting @damianam review

**Comment by boegel** [comment]
OK, problem was that the `develop` branch is a protected branch, where only I had push rights on...

I've removed that restriction (note to self: via https://github.com/easybuilders/easybuild-framework/settings/branches/develop)

**Pull request merged**
